# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

#SEO Settigs
title: blank # the website title (if blank, full name will be used instead)
description: >
  Enea Manzi - Cyber Security M.Sc. Student at the University of Milan. 
  Portfolio featuring projects in Cloud Security, Kubernetes, Docker, and Network Security.
author: Enea Manzi
keywords: >
  Enea Manzi, Cyber Security, Cloud Security, Network Security,
  Kubernetes, Docker, DevSecOps, Python, Bash, C, Linux,
  Risk Management, GDPR, Data Protection, Incident Response,
  REST API, Security Engineering, University of Milan,
  Sicurezza Informatica, Sicurezza delle Reti, Milano
url: https://eneamanzi.github.io
baseurl: "" # the subpath of your site, e.g. /blog/. Leave blank for root

first_name: Enea
last_name: Manzi
contact_note: #TODO

footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
  Photos from <a href="https://unsplash.com" target="_blank">Unsplash</a>.

#icon: 🌐 # the emoji used as the favicon (alternatively, provide image name in /assets/img/)
icon: favicon.png

last_updated: false # set to true if you want to display last updated in the footer
impressum_path: # set to path to include impressum link in the footer, use the same path as permalink in a page, helps to conform with EU GDPR
back_to_top: true # set to false to disable the back to top button

# -----------------------------------------------------------------------------
# Jekyll Polyglot
# -----------------------------------------------------------------------------
languages: ["en", "it"]
default_lang: "en"
exclude_from_localization:
  [
    "assets",
    "bin",
    "_sass",
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor",
  ]
parallel_localization: false
lang_from_path: true # <--- Importante: aiuta il plugin a capire la lingua dalla cartella
country_flag: true # set true for allowing flag symbol in language toggle

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
search_enabled: false
socials_in_search: true
posts_in_search: true

# Dimensions
max_width: 930px

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------
# Display links to the page with a preview object on social media.
# see https://schema.org/docs/faq.html for more information
serve_og_meta: true # Include Open Graph meta tags in the HTML head
serve_schema_org: true # Include Schema.org in the HTML head
og_image: /assets/img/cv_pic_resized.png # The site-wide (default for all links) Open Graph preview image

enable_google_verification: true
google_site_verification: _ybgqp15m9ukW-jOwmlr56m-S002Jvjb7iUp57SaXvM

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  projects:
    output: true
  #   output: true

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Markdown and syntax highlight
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Includes & excludes
include: ["_pages", "_scripts"]
exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - docker-compose-slim.yml
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - lighthouse_results/
  - package.json
  - package-lock.json
  - _pages/about_einstein.md
  - purgecss.config.js
  - README.md
  - readme_preview/
  - vendor
  - TODO.md
keep_files:
  - CNAME
  - .nojekyll

# Plug-ins
plugins:
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-sitemap
  - jekyll-terser
  - jemoji
  - jekyll-polyglot

# Sitemap settings
defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

sass:
  style: compressed

# -----------------------------------------------------------------------------
# Jekyll Minifier
# -----------------------------------------------------------------------------

jekyll-minifier:
  compress_javascript: false # set to false since we are using terser as the js minifier
  exclude: ["robots.txt", "assets/js/search/*.js"]

# -----------------------------------------------------------------------------
# Terser
# -----------------------------------------------------------------------------

terser:
  compress:
    drop_console: true

# -----------------------------------------------------------------------------
# Jekyll Link Attributes
# -----------------------------------------------------------------------------

# These are the defaults
external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank
  exclude:

# -----------------------------------------------------------------------------
# Responsive WebP Images
# -----------------------------------------------------------------------------

# MAKE SURE imagemagick is installed and on your PATH before enabling imagemagick. In a terminal, run:
#   convert -version
imagemagick:
  enabled: true # enables responsive images for your site (recommended, see https://github.com/alshedivat/al-folio/issues/537)
  widths:
    - 480
    - 800
    - 1400
  input_directories:
    - assets/img/
  input_formats:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".tiff"
    - ".gif"
  output_formats:
    webp: "-quality 85"

# Lazy loading images
#   If you enable lazy loading, all images will add the loading="lazy" attribute.
#   This will make your site load faster, but it may not be supported in all browsers.
#   You can also set loading="" to other values for specific images to override the default behavior.
#   Options: "auto", "eager", "lazy"
#   See https://web.dev/browser-level-image-lazy-loading/ for more information.
lazy_loading_images: true # enables lazy loading of images (recommended)

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_masonry: true
enable_math: false
enable_darkmode: true
enable_project_categories: true
enable_medium_zoom: true
enable_progressbar: true

# -----------------------------------------------------------------------------
# Library versions
# -----------------------------------------------------------------------------

# Add the url, version and integrity hash of the libraries you use in your site.
# The integrity hash is used to ensure that the library is not tampered with.
# Integrity hashes not provided by the libraries were generated using https://www.srihash.org/
third_party_libraries:
  download: false # if true, download the versions of the libraries specified below and use the downloaded files

  google_fonts:
    url:
      fonts: "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:100,300,400,500,700|Material+Icons&display=swap"
  highlightjs:
    integrity:
      css:
        light: "sha256-Oppd74ucMR5a5Dq96FxjEzGF7tTw2fZ/6ksAqDCM8GY="
        dark: "sha256-nyCNAiECsdDHrr/s2OQsp5l9XeY2ZJ0rMepjCT2AkBk="
    url:
      css:
        light: "https://cdn.jsdelivr.net/npm/highlight.js@{{version}}/styles/github.min.css"
        dark: "https://cdn.jsdelivr.net/npm/highlight.js@{{version}}/styles/github-dark.min.css"
    version: "11.9.0"
  imagesloaded:
    integrity:
      js: "sha256-htrLFfZJ6v5udOG+3kNLINIKh2gvoKqwEhHYfTTMICc="
    url:
      js: https://cdn.jsdelivr.net/npm/imagesloaded@{{version}}/imagesloaded.pkgd.min.js
    version: "5.0.0"
  img-comparison-slider:
    integrity:
      css: "sha256-3qTIuuUWIFnnU3LpQMjqiXc0p09rvd0dmj+WkpQXSR8="
      js: "sha256-EXHg3x1K4oIWdyohPeKX2ZS++Wxt/FRPH7Nl01nat1o="
      map: "sha256-3wfqS2WU5kGA/ePcgFzJXl5oSN1QsgZI4/edprTgX8w="
    url:
      css: "https://cdn.jsdelivr.net/npm/img-comparison-slider@{{version}}/dist/styles.min.css"
      js: "https://cdn.jsdelivr.net/npm/img-comparison-slider@{{version}}/dist/index.min.js"
      map: "https://cdn.jsdelivr.net/npm/img-comparison-slider@{{version}}/dist/index.js.map"
    version: "8.0.6"
  jquery:
    integrity:
      js: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
    url:
      js: "https://cdn.jsdelivr.net/npm/jquery@{{version}}/dist/jquery.min.js"
    version: "3.6.0"
  mathjax:
    integrity:
      js: "sha256-MASABpB4tYktI2Oitl4t+78w/lyA+D7b/s9GEP0JOGI="
    url:
      js: "https://cdn.jsdelivr.net/npm/mathjax@{{version}}/es5/tex-mml-chtml.js"
    version: "3.2.2"
  masonry:
    integrity:
      js: "sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI="
    url:
      js: "https://cdn.jsdelivr.net/npm/masonry-layout@{{version}}/dist/masonry.pkgd.min.js"
    version: "4.2.2"
  mdb:
    integrity:
      css: "sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw="
      css_map: "sha256-iYYMNfsJdVZjvsebJulg09miBXM4/GMTJgv1u5EZFFM="
      js: "sha256-NdbiivsvWt7VYCt6hYNT3h/th9vSTL4EDWeGs5SN3DA="
      js_map: "sha256-UPgyn4YNsT0khkBK5553QwhnlbTlU0aa+igyc6qP1bE="
    url:
      css: "https://cdn.jsdelivr.net/npm/mdbootstrap@{{version}}/css/mdb.min.css"
      css_map: "https://cdn.jsdelivr.net/npm/mdbootstrap@{{version}}/css/mdb.min.css.map"
      js: "https://cdn.jsdelivr.net/npm/mdbootstrap@{{version}}/js/mdb.min.js"
      js_map: "https://cdn.jsdelivr.net/npm/mdbootstrap@{{version}}/js/mdb.min.js.map"
    version: "4.20.0"
  medium_zoom:
    integrity:
      js: "sha256-ZgMyDAIYDYGxbcpJcfUnYwNevG/xi9OHKaR/8GK+jWc="
    url:
      js: "https://cdn.jsdelivr.net/npm/medium-zoom@{{version}}/dist/medium-zoom.min.js"
    version: "1.1.0"
  photoswipe:
    integrity:
      js: "sha256-VCBpdxvrNNxGHNuTdNqK9kPFkev2XY7DYzHdmgaB69Q="
    url:
      css: "https://cdn.jsdelivr.net/npm/photoswipe@{{version}}/dist/photoswipe.min.css"
      js: "https://cdn.jsdelivr.net/npm/photoswipe@{{version}}/dist/photoswipe.esm.min.js"
    version: "5.4.4"
  photoswipe-lightbox:
    integrity:
      js: "sha256-uCw4VgT5DMdwgtjhvU9e98nT2mLZXcw/8WkaTrDd3RI="
    url:
      js: "https://cdn.jsdelivr.net/npm/photoswipe@{{version}}/dist/photoswipe-lightbox.esm.min.js"
    version: "5.4.4"
  polyfill:
    url:
      js: "https://cdnjs.cloudflare.com/polyfill/v{{version}}/polyfill.min.js?features=es6"
    version: "3"

# -----------------------------------------------------------------------------
# Get external JSON data
# -----------------------------------------------------------------------------

#jekyll_get_json:
#  - data: resume
#    json: assets/json/resume.json # it can also be an url
#
#jsonresume:
#  - basics
#  - work
#  - education
#  - publications
#  - projects
#  - volunteer
#  - awards
#  - certificates
#  - skills
#  - languages
#  - interests
#  - references
